name: Deploy Python App to Elastic Beanstalk

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pip install pytest
          pytest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to Elastic Beanstalk
        uses: aws-actions/aws-elasticbeanstalk-deploy@v1
        with:
          aws-region: us-east-1
          application-name: my-python-app
          environment-name: my-python-app-prod
          solution-stack-name: '64bit Amazon Linux 2023 v4.3.0 running Python 3.11'
          create-application-if-not-exists: true
          create-environment-if-not-exists: true
          wait-for-deployment: false
          create-s3-bucket-if-not-exists: true
          option-settings: |
            [
              {
                "Namespace": "aws:autoscaling:launchconfiguration",
                "OptionName": "IamInstanceProfile",
                "Value": "aws-elasticbeanstalk-ec2-role"
              },
              {
                "Namespace": "aws:elasticbeanstalk:environment",
                "OptionName": "ServiceRole",
                "Value": "aws-elasticbeanstalk-service-role"
              },
              {
                "Namespace": "aws:ec2:instances",
                "OptionName": "InstanceTypes",
                "Value": "t3.micro"
              },
              {
                "Namespace": "aws:elasticbeanstalk:cloudwatch:logs",
                "OptionName": "StreamLogs",
                "Value": "true"
              }
            ]
